services:
  app:
      container_name: RocketUpload
      image: ubuntu:22.04
      command: sh -c "cd /; ./rocket_upload"
      volumes:
        - ./rocket_upload:/rocket_upload
      environment:
        - ROCKET_PORT=80
      ports:
        - "80:80"
      restart: always
